### ISSUE TITLE
Application rendering just black screen.

### ISSUE THREAD

**Issue by jeevjyot** [rhashimoto/TangoFrameCapture#2]
I am trying to run your application, the screen is just being black, it is not rendering the camera image. when i tried looking into verbose, it shows this error

10-07 11:48:30.132 7453-7453/com.shoestringresearch.tango.capture E/VersionCode: 999999999

10-07 11:48:30.624 7453-7453/com.shoestringresearch.tango.capture E/tango-client-api-jni: Unable to get method ref for onPointCloudAvailable

Any insights on this? thanks in advance, i want to convert the tango frame into RGB and eventually into grayscale.

**Comment by rhashimoto** [comment]
I haven't run this app in a while. It is possible that the Tango API has made incompatible changes in the past 1.5 years.
